---
- name: Verify that required variables are defined
  assert:
    that:
      - "{{ item }}  is defined"
      - "{{ item }} | length > 0"
      - "{{ item }} != None"
    fail_msg: "{{ item }} needs to be set for the role to work"
    success_msg: "Required variable {{ item }} is defined"
  changed_when: false
  diff: false
  loop:
    - "postfix_mydomain"
    - "postfix_myhostname"
    - "postfix_mynetworks"
    - "postfix_virtual_alias_domains"
    - "postfix_aliases"
    - "postfix_ipv4"
    - "postfix_ipv6"

- name: Verify that required variables are defined
  assert:
    that:
      - "item  is defined"
      - "item != None"
    fail_msg: "{{ item }} needs to be set for the role to work"
    success_msg: "Required variable {{ item }} is defined"
  changed_when: false
  loop:
    - "{{ postfix_dkim_enabled }}"

- name: Verify that required variables are defined for DKIM
  assert:
    that:
      - "{{ item }}  is defined"
      - "{{ item }} != None"
    fail_msg: "{{ item }} needs to be set for the role to work"
    success_msg: "Required variable {{ item }} is defined"
  changed_when: false
  loop:
    - "postfix_dkim_trustedhosts"
    - "postfix_dkim_keys"
    - "postfix_dkim_keytable"
    - "postfix_dkim_signingtable"
    - "postfix_dkim_trustedhosts"
  when: postfix_dkim_enabled
