---
- name: Edited ownership of /var/mail
  ansible.builtin.file:
    path: /var/mail/
    state: directory
    owner: vmail
    group: vmail
    # set uid for group
    mode: u=rwx-s,g=rwx,o=,g+s,+t
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Generate Diffie-Hellman parameters with size ({{ postfix_dovecot_dh_params_size }} bits)
  community.crypto.openssl_dhparam:
    path: /etc/dovecot/dhparams.pem
    size: "{{ postfix_dovecot_dh_params_size }}"
    state: present
  become: true
  # I disagree with name[template], as it is sort of at the end here
  tags:
    - skip_ansible_lint

- name: Copy dovecot configuration file
  ansible.builtin.template:
    src: dovecot/{{ config }}.j2
    dest: "/etc/dovecot/{{ config }}"
    validate: doveconf %s
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  loop:
    - dovecot.conf
    - conf.d/10-master.conf
    - conf.d/10-auth.conf
    - conf.d/10-mail.conf
    - conf.d/10-ssl.conf
    - deny-users
  loop_control:
    loop_var: config
  notify: restart dovecot
