---
- name: Adding existing user clamav to amavis group
  ansible.builtin.user:
    name: clamav
    groups: amavis
    append: true
  become: true

- name: Adding existing user postfix user to opendkim group
  ansible.builtin.user:
    name: postfix
    groups: amavis
    append: true
  become: true

- name: Add opendkim and policyd-spf users
  ansible.builtin.user:
    name: "{{ user_name }}"
    state: present
    system: true
  become: true
  loop:
    - opendkim
    - policyd-spf
  loop_control:
    loop_var: user_name
