---
- name: Adding existing user clamav to amavis group
  ansible.builtin.user:
    name: clamav
    groups: amavis
    append: true
  become: true

- name: Adding existing user postfix user to opendkim group
  ansible.builtin.user:
    name: postfix
    groups: amavis
    append: true
  become: true

- name: Add opendkim and policyd-spf users
  ansible.builtin.user:
    name: "{{ user_name }}"
    state: present
    system: true
  become: true
  loop:
    - opendkim
    - policyd-spf
  loop_control:
    loop_var: user_name

- name: Ensure group "vmail" exists
  ansible.builtin.group:
    name: vmail
    state: present
  become: true

- name: Add vmail user for dovecot
  ansible.builtin.user:
    name: vmail
    groups: vmail
    home: /var/mail/
    create_home: true
    system: true
  become: true

- name: Add dovecot user
  ansible.builtin.user:
    name: dovecot
    system: true
  become: true
