---
- name: Generate virtual database for postfix
  command: sudo postmap /etc/postfix/virtual
  become: true
  listen: "generate virtual aliasdb"

- name: enable and restart Postfix service
  ansible.builtin.systemd:
    name: postfix
    state: restarted
    enabled: true
  become: true
  listen: "restart postfix"

- name: update aliases
  ansible.builtin.command: newaliases
  become: true
  listen: "update aliases"

- name: restart dovecot
  ansible.builtin.systemd:
    name: dovecot
    state: restarted
    enabled: true
  become: true
  listen: "restart dovecot"

- name: restart amavis
  ansible.builtin.systemd:
    name: amavis
    state: restarted
    enabled: true
  become: true
  listen: "restart amavis"

- name: restart opendkim
  ansible.builtin.systemd:
    name: opendkim
    state: restarted
    enabled: true
  become: true
  listen: "restart opendkim"

- name: restart opendmarc
  ansible.builtin.systemd:
    name: opendmarc
    state: restarted
    enabled: true
  become: true
  listen: "restart opendmarc"
